//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPXUtils.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPXUtils.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] gpx_complex_waypoint {
            get {
                object obj = ResourceManager.GetObject("gpx_complex_waypoint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_invalid_root_element {
            get {
                object obj = ResourceManager.GetObject("gpx_invalid_root_element", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_multiple_routes {
            get {
                object obj = ResourceManager.GetObject("gpx_multiple_routes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_named_route {
            get {
                object obj = ResourceManager.GetObject("gpx_named_route", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_real {
            get {
                object obj = ResourceManager.GetObject("gpx_real", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_named_track {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_named_track", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_route {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_route", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_track {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_track", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_waypoint_incorrect_lat {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_waypoint_incorrect_lat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_waypoint_incorrect_lon {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_waypoint_incorrect_lon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_waypoint_missing_lat {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_waypoint_missing_lat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_waypoint_missing_lon {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_waypoint_missing_lon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_simple_waypoints {
            get {
                object obj = ResourceManager.GetObject("gpx_simple_waypoints", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_track_multiple_segments {
            get {
                object obj = ResourceManager.GetObject("gpx_track_multiple_segments", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_waypoint_with_comment {
            get {
                object obj = ResourceManager.GetObject("gpx_waypoint_with_comment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_waypoint_with_desc {
            get {
                object obj = ResourceManager.GetObject("gpx_waypoint_with_desc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_waypoint_with_elevation {
            get {
                object obj = ResourceManager.GetObject("gpx_waypoint_with_elevation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_waypoint_with_name {
            get {
                object obj = ResourceManager.GetObject("gpx_waypoint_with_name", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_waypoint_with_time {
            get {
                object obj = ResourceManager.GetObject("gpx_waypoint_with_time", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
