//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchGPX2OSM.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchGPX2OSM.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] gpx_two_points_different_ways {
            get {
                object obj = ResourceManager.GetObject("gpx_two_points_different_ways", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_two_points_same_segment {
            get {
                object obj = ResourceManager.GetObject("gpx_two_points_same_segment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_two_points_same_segment_reverse {
            get {
                object obj = ResourceManager.GetObject("gpx_two_points_same_segment_reverse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_two_points_same_way {
            get {
                object obj = ResourceManager.GetObject("gpx_two_points_same_way", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] gpx_two_points_same_way_reverse {
            get {
                object obj = ResourceManager.GetObject("gpx_two_points_same_way_reverse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_find_candidates_test {
            get {
                object obj = ResourceManager.GetObject("osm_find_candidates_test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_more_uturns_one_way {
            get {
                object obj = ResourceManager.GetObject("osm_more_uturns_one_way", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_reconstruct {
            get {
                object obj = ResourceManager.GetObject("osm_reconstruct", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_simle_uturn {
            get {
                object obj = ResourceManager.GetObject("osm_simle_uturn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_test_case_1 {
            get {
                object obj = ResourceManager.GetObject("osm_test_case_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_test_case_2 {
            get {
                object obj = ResourceManager.GetObject("osm_test_case_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] osm_uturns_one_way {
            get {
                object obj = ResourceManager.GetObject("osm_uturns_one_way", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
